# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d774f49e46da36ecfece5caa37c6842fcae191d0c1d0340ccb756cc6c84207867177990c36a61cde5db8b1e600fd7d8d6263007bda2f93b8a821af1b32973fa

test:
  secret_key_base: 288665624e861b0e7ec51f8d7de71b60b90091baa9188eb37c0b05a06aa4aab580ebe771feaeef82cd78f56189d05476c63c2849e50cb7b7c29bb0664cca390f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
